//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCSTimbraCFDI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://localhost/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/RegistraEmisor", ReplyAction="*")]
        DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorResponse RegistraEmisor(DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraCFDI", ReplyAction="*")]
        DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIResponse TimbraCFDI(DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDI", ReplyAction="*")]
        DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIResponse CancelaCFDI(DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneCFDI", ReplyAction="*")]
        DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIResponse ObtieneCFDI(DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraEmisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraEmisor", Namespace="http://localhost/", Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorRequestBody Body;
        
        public RegistraEmisorRequest() {
        }
        
        public RegistraEmisorRequest(DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class RegistraEmisorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string base64Cer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string base64Key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasena;
        
        public RegistraEmisorRequestBody() {
        }
        
        public RegistraEmisorRequestBody(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.base64Cer = base64Cer;
            this.base64Key = base64Key;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraEmisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraEmisorResponse", Namespace="http://localhost/", Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorResponseBody Body;
        
        public RegistraEmisorResponse() {
        }
        
        public RegistraEmisorResponse(DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class RegistraEmisorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType RegistraEmisorResult;
        
        public RegistraEmisorResponseBody() {
        }
        
        public RegistraEmisorResponseBody(DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType RegistraEmisorResult) {
            this.RegistraEmisorResult = RegistraEmisorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraCFDI", Namespace="http://localhost/", Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIRequestBody Body;
        
        public TimbraCFDIRequest() {
        }
        
        public TimbraCFDIRequest(DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlComprobanteBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idComprobante;
        
        public TimbraCFDIRequestBody() {
        }
        
        public TimbraCFDIRequestBody(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.xmlComprobanteBase64 = xmlComprobanteBase64;
            this.idComprobante = idComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraCFDIResponse", Namespace="http://localhost/", Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIResponseBody Body;
        
        public TimbraCFDIResponse() {
        }
        
        public TimbraCFDIResponse(DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType TimbraCFDIResult;
        
        public TimbraCFDIResponseBody() {
        }
        
        public TimbraCFDIResponseBody(DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType TimbraCFDIResult) {
            this.TimbraCFDIResult = TimbraCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDI", Namespace="http://localhost/", Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIRequestBody Body;
        
        public CancelaCFDIRequest() {
        }
        
        public CancelaCFDIRequest(DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public CancelaCFDIRequestBody() {
        }
        
        public CancelaCFDIRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDIResponse", Namespace="http://localhost/", Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIResponseBody Body;
        
        public CancelaCFDIResponse() {
        }
        
        public CancelaCFDIResponse(DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType CancelaCFDIResult;
        
        public CancelaCFDIResponseBody() {
        }
        
        public CancelaCFDIResponseBody(DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType CancelaCFDIResult) {
            this.CancelaCFDIResult = CancelaCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneCFDI", Namespace="http://localhost/", Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIRequestBody Body;
        
        public ObtieneCFDIRequest() {
        }
        
        public ObtieneCFDIRequest(DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public ObtieneCFDIRequestBody() {
        }
        
        public ObtieneCFDIRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneCFDIResponse", Namespace="http://localhost/", Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIResponseBody Body;
        
        public ObtieneCFDIResponse() {
        }
        
        public ObtieneCFDIResponse(DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType ObtieneCFDIResult;
        
        public ObtieneCFDIResponseBody() {
        }
        
        public ObtieneCFDIResponseBody(DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType ObtieneCFDIResult) {
            this.ObtieneCFDIResult = ObtieneCFDIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : DemoCSTimbraCFDI.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<DemoCSTimbraCFDI.ServiceReference1.Service1Soap>, DemoCSTimbraCFDI.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorResponse DemoCSTimbraCFDI.ServiceReference1.Service1Soap.RegistraEmisor(DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorRequest request) {
            return base.Channel.RegistraEmisor(request);
        }
        
        public DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType RegistraEmisor(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena) {
            DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorRequest inValue = new DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorRequest();
            inValue.Body = new DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.base64Cer = base64Cer;
            inValue.Body.base64Key = base64Key;
            inValue.Body.contrasena = contrasena;
            DemoCSTimbraCFDI.ServiceReference1.RegistraEmisorResponse retVal = ((DemoCSTimbraCFDI.ServiceReference1.Service1Soap)(this)).RegistraEmisor(inValue);
            return retVal.Body.RegistraEmisorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIResponse DemoCSTimbraCFDI.ServiceReference1.Service1Soap.TimbraCFDI(DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIRequest request) {
            return base.Channel.TimbraCFDI(request);
        }
        
        public DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType TimbraCFDI(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIRequest inValue = new DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIRequest();
            inValue.Body = new DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            DemoCSTimbraCFDI.ServiceReference1.TimbraCFDIResponse retVal = ((DemoCSTimbraCFDI.ServiceReference1.Service1Soap)(this)).TimbraCFDI(inValue);
            return retVal.Body.TimbraCFDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIResponse DemoCSTimbraCFDI.ServiceReference1.Service1Soap.CancelaCFDI(DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIRequest request) {
            return base.Channel.CancelaCFDI(request);
        }
        
        public DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType CancelaCFDI(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIRequest inValue = new DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIRequest();
            inValue.Body = new DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            DemoCSTimbraCFDI.ServiceReference1.CancelaCFDIResponse retVal = ((DemoCSTimbraCFDI.ServiceReference1.Service1Soap)(this)).CancelaCFDI(inValue);
            return retVal.Body.CancelaCFDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIResponse DemoCSTimbraCFDI.ServiceReference1.Service1Soap.ObtieneCFDI(DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIRequest request) {
            return base.Channel.ObtieneCFDI(request);
        }
        
        public DemoCSTimbraCFDI.ServiceReference1.ArrayOfAnyType ObtieneCFDI(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIRequest inValue = new DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIRequest();
            inValue.Body = new DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            DemoCSTimbraCFDI.ServiceReference1.ObtieneCFDIResponse retVal = ((DemoCSTimbraCFDI.ServiceReference1.Service1Soap)(this)).ObtieneCFDI(inValue);
            return retVal.Body.ObtieneCFDIResult;
        }
    }
}
